# Generated by Django 4.2.7 on 2023-11-10 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('title', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('movie_duration', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('Poster', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('type', models.CharField(max_length=20)),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('registered', models.DateField()),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('shifts_taken', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shifts',
            fields=[
                ('type', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('shift_duration', models.IntegerField()),
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('movieId', models.IntegerField()),
                ('UsersId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manage_account.users')),
            ],
        ),
    ]
