# Generated by Django 4.2.7 on 2023-11-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
