# Generated by Django 4.2.7 on 2023-11-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0002_alter_users_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='type',
            field=models.CharField(choices=[('Super', 'Super'), ('Volunteer', 'Volunteer')], default='Volunteer', max_length=20),
        ),
    ]
