# Generated by Django 4.2.7 on 2023-11-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0003_alter_users_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='shifts_taken',
            field=models.IntegerField(default=0),
        ),
    ]
