# Generated by Django 4.2.7 on 2023-11-13 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0004_alter_users_shifts_taken'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shifts',
            old_name='movieId',
            new_name='movie_id',
        ),
        migrations.RenameField(
            model_name='shifts',
            old_name='UsersId',
            new_name='users_id',
        ),
    ]
