# Generated by Django 4.2.7 on 2023-11-13 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manage_account', '0006_alter_movies_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shifts',
            name='movie_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_account.movies'),
        ),
        migrations.AlterField(
            model_name='shifts',
            name='users_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='manage_account.users'),
        ),
    ]
